# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200612_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
