# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200612_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
